//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalManagementSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int ID { get; set; }
        public int Product_ID { get; set; }
        public int Qty_base { get; set; }
        public System.DateTime Date_time_mod { get; set; }
        public int Supplier_ID { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual Product_details Product_details { get; set; }
    }
}
