//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalManagementSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions_View
    {
        public string Customer_Name { get; set; }
        public string Product_Name { get; set; }
        public int Qunatity_Bought { get; set; }
        public string Expr1 { get; set; }
        public Nullable<System.DateTime> Date_Purchased { get; set; }
        public string Billing_Address { get; set; }
    }
}
